name: Lighthouse Report

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI on Vercel site
        run: lhci autorun --config=lighthouserc.cjs

      - name: Commit report
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/lighthouse-report
          git commit -m "Add Lighthouse report from Vercel deploy" || echo "No changes to commit"
          git push

      - name: Update README with report link
        run: |
          REPORT_FILE=$(find docs/lighthouse-report -name "*.report.html" | sort | tail -n 1)
          if [ -z "$REPORT_FILE" ]; then
            echo "No report file found!"
            exit 1
          fi
          RELATIVE_URL="https://revixxd.github.io/formaSint/${REPORT_FILE#docs/}"
          LINK_LINE="📊 [Lighthouse Report]($RELATIVE_URL)"

          if grep -q "Lighthouse Report" README.md; then
            sed -i "s|.*Lighthouse Report.*|$LINK_LINE|" README.md
          else
            echo -e "\n$LINK_LINE" >> README.md
          fi

          git add README.md
          git commit -m "Update README with latest Lighthouse report link" || echo "No changes to commit"
          git push
